[package]
name = "heatseeker"
version = "1.5.2"
authors = ["Ryan Schmitt <rschmitt@pobox.com>"]
description = "A fast, robust, and portable fuzzy finder."
license = "MIT"
readme = "README.md"
documentation = "https://github.com/rschmitt/heatseeker"
homepage = "https://github.com/rschmitt/heatseeker"
repository = "https://github.com/rschmitt/heatseeker"
build = "build.rs"
exclude = ["*.nuspec", "*.bat", "*.rb", "*.yml"]

[[bin]]
name = "hs"
path = "src/main.rs"

[dependencies]
libc = "0.2.31"
getopts = "0.2.15"
unicode-width = "0.1.4"
num_cpus = "1.7.0"
crossbeam = "0.3.0"
local-encoding = "0.2.0"

[build-dependencies]
time = "0.1.38"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
kernel32-sys = "0.2.2"
